"""Database cretion

Revision ID: 08fa42879e01
Revises: 
Create Date: 2024-06-16 20:01:54.433781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fa42879e01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence',
                    sa.Column('id_sentence', sa.Integer(), nullable=False),
                    sa.Column('sent_id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id_sentence')
    )
    op.create_table('token',
                    sa.Column('id_token', sa.Integer(), nullable=False),
                    sa.Column('id_sentence', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('form', sa.String(), nullable=True),
                    sa.Column('lemma', sa.String(), nullable=True),
                    sa.Column('upos', sa.String(), nullable=False),
                    sa.Column('xpos', sa.String(), nullable=True),
                    sa.Column('feats', sa.String(), nullable=True),
                    sa.Column('head', sa.Integer(), nullable=False),
                    sa.Column('deprel', sa.String(), nullable=True),
                    sa.Column('deps', sa.String(), nullable=True),
                    sa.Column('misc', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['id_sentence'], ['sentence.id_sentence'], ),
                    sa.PrimaryKeyConstraint('id_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('sentence')
    # ### end Alembic commands ###
